/**
 * Feature #30 — Shareable Resource Cards
 *
 * Generates a shareable PNG card with the resource name, URL, description,
 * your rating, and FMHY branding — for Discord/Reddit.
 *
 * Uses Canvas API to render client-side (no external service needed).
 */
(function (global) {
  "use strict";
  global.FMHY = global.FMHY || {};

  const NAME = "shareCards";
  let initialized = false;

  async function generateCard(url, title, rating, note) {
    const canvas = document.createElement("canvas");
    canvas.width = 1200;
    canvas.height = 630;
    const ctx = canvas.getContext("2d");

    // Background gradient
    const grad = ctx.createLinearGradient(0, 0, 1200, 630);
    grad.addColorStop(0, "#7c3aed");
    grad.addColorStop(1, "#2563eb");
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, 1200, 630);

    // Decorative bolt
    ctx.fillStyle = "rgba(250, 204, 21, 0.15)";
    ctx.beginPath();
    ctx.moveTo(950, 100);
    ctx.lineTo(1100, 100);
    ctx.lineTo(1000, 300);
    ctx.lineTo(1100, 300);
    ctx.lineTo(900, 530);
    ctx.lineTo(1000, 350);
    ctx.lineTo(900, 350);
    ctx.closePath();
    ctx.fill();

    // Brand bar
    ctx.fillStyle = "#facc15";
    ctx.fillRect(60, 60, 8, 510);

    // Header
    ctx.fillStyle = "rgba(255,255,255,0.85)";
    ctx.font = "600 24px Inter, system-ui, sans-serif";
    ctx.fillText("FMHY SUPERCHARGED", 100, 110);

    // Title
    ctx.fillStyle = "#ffffff";
    ctx.font = "700 56px Inter, system-ui, sans-serif";
    wrapText(ctx, title || url, 100, 200, 1000, 70, 3);

    // URL
    ctx.fillStyle = "rgba(255,255,255,0.7)";
    ctx.font = "400 22px 'SF Mono', Menlo, monospace";
    let shortUrl = url;
    if (shortUrl.length > 80) shortUrl = shortUrl.slice(0, 77) + "…";
    ctx.fillText(shortUrl, 100, 440);

    // Rating
    if (rating && rating.stars) {
      ctx.font = "48px serif";
      ctx.fillStyle = "#facc15";
      ctx.fillText("*".repeat(rating.stars) + "".repeat(5 - rating.stars), 100, 510);
      if (rating.review) {
        ctx.fillStyle = "rgba(255,255,255,0.85)";
        ctx.font = "italic 22px Inter, system-ui, sans-serif";
        ctx.fillText(`"${rating.review}"`, 320, 505);
      }
    }

    // Footer
    ctx.fillStyle = "rgba(255,255,255,0.5)";
    ctx.font = "400 18px Inter, system-ui, sans-serif";
    ctx.fillText("Generated by FMHY Supercharged • fmhy.net", 100, 590);

    // Trigger download
    canvas.toBlob((blob) => {
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `fmhy-card-${FMHY.Dom.hash(url)}.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(a.href), 1000);
    }, "image/png");

    // Also generate a markdown snippet
    const md = `**[${title}](${url})**\n\n${rating && rating.stars ? "".repeat(rating.stars) + "/5" : ""}${rating && rating.review ? " — " + rating.review : ""}\n\n_Generated by [FMHY Supercharged](https://fmhy.net)_`;
    await FMHY.Dom.copyToClipboard(md);
  }

  function wrapText(ctx, text, x, y, maxWidth, lineHeight, maxLines) {
    const words = text.split(" ");
    let line = "";
    let lines = [];
    for (const word of words) {
      const test = line ? line + " " + word : word;
      if (ctx.measureText(test).width > maxWidth && line) {
        lines.push(line);
        line = word;
        if (lines.length === maxLines - 1) break;
      } else {
        line = test;
      }
    }
    if (lines.length < maxLines) lines.push(line);
    if (lines.length === maxLines) {
      let last = lines[maxLines - 1];
      while (ctx.measureText(last + "…").width > maxWidth && last.length > 0) {
        last = last.slice(0, -1);
      }
      lines[maxLines - 1] = last + "…";
    }
    lines.forEach((l, i) => ctx.fillText(l, x, y + i * lineHeight));
  }

  async function handleShareMessage(url, text) {
    const [rating, note] = await Promise.all([
      FMHY.Storage.getRating(url),
      FMHY.Storage.getNote(url)
    ]);
    await generateCard(url, text || url, rating, note);
  }

  global.FMHY.registerFeature(NAME, {
    init() {
      if (initialized) return;
      initialized = true;
      // Add a "share card" button next to each resource link
      const addButtons = () => {
        FMHY.Dom.getResourceLinks().forEach(({ element, href, text }) => {
          if (element.dataset.fmhyShareBtn) return;
          element.dataset.fmhyShareBtn = "1";
          const btn = FMHY.Dom.el("span", {
            class: "fmhy-share-btn",
            title: "Generate share card",
            role: "button",
            tabindex: "0"
          }, "");
          btn.addEventListener("click", (e) => {
            e.preventDefault(); e.stopPropagation();
            handleShareMessage(href, text);
          });
          element.appendChild(btn);
        });
      };
      addButtons();
      FMHY.onPageChange(addButtons);
    },
    onMessage(msg) {
      if (msg.type === "generateShareCard" && msg.url) {
        handleShareMessage(msg.url, msg.text || msg.url);
        return true;
      }
      return false;
    },
    generateCard
  });
})(typeof globalThis !== "undefined" ? globalThis : (typeof self !== "undefined" ? self : this));
